<a href="https://colab.research.google.com/github/coldsober-irene/NLP-fellowship/blob/main/my_colab_setup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import json 
import requests
import os

def extractor(filePath = "", link = "", outputFormat = ""):
  decision = None
  if link and not filePath:
    pass
  elif filePath and not link:
    pass
  elif link and filePath:
    print("please enter 1 for link preference or 2 for filePath")
    decision = int(input("decision: "))
  else:
    print("please make sure you have either selected the json file or you passed an API instead")
  
  def baseOnDecision():
    if decision == 1:
      onlineData = requests.get(link)
    
# CHECK IN DIRECTORY
# files = os.listdir()
# print(files)
  

['.config', 'irene', 'drive', 'pc.png', 'sample_data']


In [ ]:
# check the image
import cv2
import pandas as pd

image = cv2.imread('/content/drive/MyDrive/NLP fellowship/pcDark.png')
csv_file = "/content/drive/MyDrive/NLP fellowship/machine-readable-business-employment-data-june-2022-quarter.csv"
print(image[3])

with open(csv_file) as file:
  lines = file.readlines()
  # get first line
  print(lines[0]) 

# SHOW THE FILE USING PANDAS
df = pd.read_csv(csv_file)
# show heading
df.head()

[[0 0 0]
 [0 0 0]
 [0 0 0]
 ...
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5



Series_reference   Period  Data_value Suppressed STATUS   UNITS  Magnitude  \
0      BDCQ.SEA1AA  2011.06     80078.0        NaN      F  Number          0   
1      BDCQ.SEA1AA  2011.09     78324.0        NaN      F  Number          0   
2      BDCQ.SEA1AA  2011.12     85850.0        NaN      F  Number          0   
3      BDCQ.SEA1AA  2012.03     90743.0        NaN      F  Number          0   
4      BDCQ.SEA1AA  2012.06     81780.0        NaN      F  Number          0   

                          Subject                            Group  \
0  Business Data Collection - BDC  Industry by employment variable   
1  Business Data Collection - BDC  Industry by employment variable   
2  Business Data Collection - BDC  Industry by employment variable   
3  Business Data Collection - BDC  Industry by employment variable   
4  Business Data Collection - BDC  Industry by employment variable   

  Series_title_1                     Series_title_2 Series_title_3  \
0    Filled jobs  Agriculture, Forestry and Fishing         Actual   
1    Filled jobs  Agriculture, Forestry and Fishing         Actual   
2    Filled jobs  Agriculture, Forestry and Fishing         Actual   
3    Filled jobs  Agriculture, Forestry and Fishing         Actual   
4    Filled jobs  Agriculture, Forestry and Fishing         Actual   

   Series_title_4  Series_title_5  
0             NaN             NaN  
1             NaN             NaN  
2             NaN             NaN  
3             NaN             NaN  
4             NaN             NaN

In [ ]:
# importing the files from google drive using codes
from google.colab import drive
# mount the drive to the colab
drive.mount("/content/irene")

Mounted at /content/irene


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# CLONE THE DATA FROM GITHUB
!git clone https://github.com/Digital-Umuganda/common_voice_dataset_rw.git


fatal: destination path 'common_voice_dataset_rw' already exists and is not an empty directory.


In [ ]:
with open("/content/common_voice_dataset_rw/partner-10.rw.txt", "r") as f:
  data = f.readlines()
  print(data[0:3])

['Yamweretse ishusho yishuri ryisumbuye.\n', 'Uyu ni umurimo ugomba gukorwa n’ubwoko bwayo\n', 'Ijoro ryari ricuze umwijima, ariko Zuba iyo gukiranuka yarabagiranaga kuri bo.\n']


In [ ]:
import os
p = "/content/my_drive"
if not os.path.exists(p):
  os.mkdir(p)

False

In [ ]:
!git clone https://github.com/coldsober-irene/NLP-fellowship.git


Cloning into 'NLP-fellowship'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 15 (delta 4), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (15/15), done.


In [89]:
import requests
import json
import numpy as np
# TODO: Get products from https://dummyjson.com

# Enter code here #
api = "https://dummyjson.com/products"
data = requests.get(api).json()

all_products = data['products']
#  get unique category and its related brands
unique_categories = []
for product in all_products:
  unique_categories.append(product['category'])
unique_categories = list(set(unique_categories))

# ready categories to accept brands
cats = {}
# category and its corresponding brands
for cat in unique_categories:
  cats.setdefault(cat, [])

# get brands in a give category
for cat in unique_categories:
  for prod in all_products:
    if prod['category'] == cat:
      cats[cat].append({"brand":prod["brand"],"title":prod['title'], "price":prod['price']})
cats

# update data
updateData = {}

for cat in unique_categories:
  cat_info = cats[cat]
  brands = []
  prices = 0
  count = 0
  items = []
  for info in cat_info:
    brands.append(info['brand'])
    items.append(info['title'])
    prices += info['price']
    count += 1
  # update the data
  av_price = round((prices / count),1)
  updateData.setdefault(cat, {"brands":brands, "items":items,"average price": prices})

brands_items = {}
for brand in list(set(brands)):
  brands_items.setdefault(brand, [[],[]])
  for product in all_products:
    if product['brand'] == brand:
      brands_items[brand][0].append(product['title']) 
      brands_items[brand][1].append(product['price'])
  # get average price
  prices = brands_items[brand][1] 
  price_len = len(prices)
  tot = 0
  for price in prices:
    tot += price
  # update average price
  av = round((tot / price_len), 1)
  brands_items[brand][0].append(av)
  #del brands_items[brand][1]

# print(set(brands))
brand_items_keys = list(brands_items.keys())
for key in brand_items_keys:
  del brands_items[key][1]
  rest_data = brands_items[key][0]
  brands_items[key] = rest_data
print(brands_items)

# show update data
# print(updateData)

# create new json file
with open("newJson.json", "w") as js:
  json.dump(updateData, js)

{'Huawei': ['Huawei P30', 499.0], 'Apple': ['iPhone 9', 'iPhone X', 724.0], 'OPPO': ['OPPOF19', 280.0], 'Samsung': ['Samsung Universe 9', 'Samsung Galaxy Book', 1374.0]}


In [ ]:
import json 
import requests
import os
import csv

def jsonExtracter(filePath = "", link = "", outputFormat = "csv"):
  decision = None
  data = None
  if link and not filePath:
    data = requests.get(link).text
    # print("DATA: ", data)
  elif filePath and not link:
    with open(filePath, "r") as file:
      data = file.load(file)
      print(data)
  elif link and filePath:
    print("please enter 1 for link preference or 2 for filePath")
    decision = int(input("decision: "))
  else:
    print("please make sure you have either selected the json file or you passed an API instead")
  # return data

  dict_data = json.loads(data)
  # GET KEYS
  ALL_DATA = dict_data['MRData']
  print(ALL_DATA)
  all_keys = dict_data['MRData'].keys()
  only_keys = list(all_keys)

  # ALL RACES
  all_races = ALL_DATA['RaceTable']['Races']
  all_seasons = ALL_DATA['RaceTable']['season']
  # print(all_seasons)

  all_results = []
  #
  for race in all_races:
    result = race['Results']
    print(result[0]["Driver"])
    # all_results.append({"seaon": ALL_DATA['RaceTable']["season"], "result": result})
    all_results.append([result[0]["Driver"]["givenName"], result[0]["Driver"]["familyName"],
                        result[0]["Driver"]["nationality"],
                        ALL_DATA['RaceTable']["season"],  result])
  
  # WRITE TO CSV FILE
  fileName = "drivers_results.csv"
  with open(fileName, "w") as f:
    Wr = csv.writer(f)
    for row in all_results:
      Wr.writerow(row)
  
  def baseOnDecision():
    data = None
    if decision == 1:
      data = requests.get(link).text
      
    elif decision == 2:
      file_opened = open(filePath)
      data = json.load(file_opened)
    else:
      pass
    return data
  
  def releaseOutput():
    data = baseOnDecision()
    if data:
      if outputFormat == "csv":
        pass
      elif outputFormat == "text":
        pass
    # print(data)
# learn func
drivers = ['https://ergast.com/api/f1/2018/drivers/Ericsson/results.json', 
            "http://ergast.com/api/f1/2018/drivers/hamilton/results.json", 
            'https://ergast.com/api/f1/2018/drivers/Gasly/results.json'
          ]

for driver in drivers:
  jsonExtracter(link = driver)

