<a href="https://colab.research.google.com/github/coldsober-irene/NLP-fellowship/blob/main/tensorflow_1h.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow-gpu

In [ ]:
%tensorflow_version 2.x # this notebook (colab) only accept tensflow flow of version 2 and above

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [19]:
import tensorflow as tf

In [ ]:
print(tf.version) 

In [26]:
# CREATE SOME OF THE TENSORS EXAMPLES
st = tf.Variable("this is a string", tf.string) # (value, dtype)
intiger = tf.Variable(3000, tf.int16)
floater = tf.Variable(230.89, tf.float16)

In [33]:
# get the rank in tensor
st_rank = tf.rank(st)
st_rank # zero rank

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [32]:
a = tf.Variable([[["yes", "20"],["cold", "false"]],[["hot", "true"],["day", "30"]]], tf.string)
tf.rank(a) # it is 3 since the arrays are nested 3 levels

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [31]:
# GET THE SHAPE 
shap = tf.shape(a)
shap

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 2], dtype=int32)>

In [34]:
# CREATE A TENSOR
tens = tf.zeros([1,3,3]) # [[[x1, x2, x3],[x1, x2, x3],[x1, x2, x3]]]
tens

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [37]:
# RESHAPE
new_tens = tf.reshape(tens, [1,9])
new_tens

<tf.Tensor: shape=(1, 9), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [38]:
# ANOTHER RESHAPE (when [3,-1] is used is to tell the tensor let me have 3 array and figure out how many items will be in each array)
new2 = tf.reshape(new_tens, [3, -1])
new2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [39]:
# another example
ten = tf.ones([4,4,5])
ten

<tf.Tensor: shape=(4, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [46]:
# newTen = tf.reshape(ten, [80])
# newTen = tf.reshape(ten, [40,-1])
newTen = tf.reshape(ten, [16, -1])
newTen

<tf.Tensor: shape=(16, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

5.0